### ISSUE TITLE
Inherit CSS table border from table to cells

### ISSUE THREAD

**Issue by wojtekw92** [ckeditor/editor-recommendations#57] opened 2017-07-27 13:30 UTC
## Introduction

Now for border settings we are using tag `<table border=1>` but this method is deprecated according to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table). Unfortunately we are not able to make quick and easy migration to CSS values. Standard `border` attribute behaviour is to set solid border with width equals to value in pixels. So we can easy transform this to `border: 1px solid;`. The problem is that when we set `border` attribute the value is inherited by cells but when we are using CSS value isn't inherited.

example: 
![screen shot 2017-07-27 at 15 18 02](https://user-images.githubusercontent.com/7364832/28672082-ff5f8798-72de-11e7-9e4f-4d96f7682293.png)

## What is the problem?
My question is how we should inherit this values to new cells in the editor. It is easy to create table with proper CSS code in the cells, but how to deal with:

* changing border of table after changing border of cell
* adding new cells using context menu or tab key

## Solution
I was thinking about adding style attribute to every cell and after every table change check cell by cell if we have to add this changes to cell but I don't think this solution is very efficiency.
What would be the best solution to make changes on the cells border? Maybe you have better idea than `style` attribute in every cell.

**Comment by mlewand** [comment] 2017-07-27 16:25
Unfortunately in the editor, compared to websites can not generate whole stylesheets - and that's the way that tables are supposed to be styled, using selectors, not inline styles.

Yea, there are multiple problems with adding border for each cell.

* it messes the output with extra CSS
* requires much more work on our end (as mentioned in "What is the problem?" section)

I'm not CSS expert, but I'm afraid there's no easy replacement for `table[border]` attribute.

**Comment by Reinmar** [comment] 2017-08-08 11:12
The styling of tables should be controlled by stylesheets. The editor should set as few attributes as possible and only allow the user to pick from predefined styles (**by classes**). That's the ideal way.

Of course, this ideal way is:

* not something what can be easily added to CKEditor 4 now, 
* not something that would satisfy everyone.

Finally, if people were really depending on the behaviour that setting border=1 gives all the cells borders too, then it makes things even more complex. It means that whatever you do there will be quite serious compatibility issues.

So the problem is that changing anything related to this attribute will already lead to problems. Therefore, I'd recommend:

* considering extracting the "table attributes" functionality to a separate plugin,
* bringing the second plugin which will allow styling tables using predefined styles.

**Comment by smartcorestudio** [comment] 2017-08-08 12:57
> bringing the second plugin which will allow styling tables using predefined styles

Very interesting. Will this classes be user-defined, configurable? In the addons now there are some solutions for those who use Bootstrap (for example: https://ckeditor.com/addon/bootstrapTable, https://ckeditor.com/addon/bttable). Do you mean something like this?

**Comment by Reinmar** [comment] 2017-08-08 13:08
Oopsie. I haven't noticed that this was reported in Editor Recommendations. My reply was focused on CKEditor 4 because the problem that we have with the attribute touches CKEditor 4 only. I don't think we should be discussing this in ER. In ER the answer may be completely different than what we might need.

The only generic piece of my answer which matches the ER project is this:

> The styling of tables should be controlled by stylesheets. The editor should set as few attributes as possible and only allow the user to pick from predefined styles (by classes). That's the ideal way.

The implementation details are beyond the scope of this project.

**Comment by Comandeer** [comment] 2017-10-26 10:57
I totally agree with @Reinmar comment and think that we could close this issue.

**Closed as completed by Comandeer** 2017-10-26 10:57 UTC
